[CmdletBinding()]
param([switch]$NoDesktopShortcut)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Program-Snapshot.ps1')
if ([string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) { throw 'LOCALAPPDATA is unavailable.' }
$sourceRoot = Split-Path -Parent $PSScriptRoot
$installRoot = Join-Path $env:LOCALAPPDATA 'Programs\NEVR-Anticheat'
$dataRoot = Join-Path $env:LOCALAPPDATA 'NEVR-Anticheat'
$startMenu = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
$desktop = [Environment]::GetFolderPath('Desktop')
$rollbackRoot = Join-Path $dataRoot 'program-rollbacks'

Assert-NEVRProgramsClosed $installRoot
$null = Assert-NEVRRegularPath $installRoot 'configs'
$programNames = @('nevr-desktop.exe', 'nevr-ac.exe', 'nevr-server.exe', 'nevr-bridge.exe', 'nevr-compat.exe')
foreach ($name in $programNames) {
    $source = Assert-NEVRRegularPath $sourceRoot $name
    if (-not (Test-Path -LiteralPath $source -PathType Leaf)) { throw "Package is incomplete: $name" }
    $null = Assert-NEVRRegularPath $installRoot $name
}
# Preserve the installed program before replacing it. Evidence is not copied:
# it already lives separately in $dataRoot and remains compatible/migrated.
if (Test-Path -LiteralPath (Join-Path $installRoot 'nevr-desktop.exe')) {
    $snapshot = New-NEVRProgramSnapshot $installRoot $rollbackRoot
    Write-Host "Verified previous program snapshot: $snapshot"
}
New-Item -ItemType Directory -Force -Path $installRoot, $dataRoot, (Join-Path $installRoot 'configs') | Out-Null
foreach ($name in $programNames) { Copy-Item -LiteralPath (Join-Path $sourceRoot $name) -Destination $installRoot -Force }
Get-ChildItem -LiteralPath $sourceRoot -Filter 'README*.txt' -File | Copy-Item -Destination $installRoot -Force
Copy-Item -LiteralPath (Join-Path $sourceRoot 'README.md') -Destination $installRoot -Force
Copy-Item -LiteralPath (Join-Path $sourceRoot 'configs\default.toml') -Destination (Join-Path $installRoot 'configs') -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Uninstall-NEVR.ps1') -Destination $installRoot -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Uninstall-NEVR.cmd') -Destination $installRoot -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Rollback-NEVR.ps1') -Destination $installRoot -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Rollback-NEVR.cmd') -Destination $installRoot -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Program-Snapshot.ps1') -Destination $installRoot -Force

$dbPath = (Join-Path $dataRoot 'nevr-anticheat.db').Replace('\', '/')
$configPath = Join-Path $installRoot 'installed.toml'
if (-not (Test-Path -LiteralPath $configPath)) {
@"
# Generated by the NEVR-Anticheat Windows installer.
# Evidence is kept outside the program folder so updates are safe.
[general]
db_path = "$dbPath"
"@ | Set-Content -LiteralPath $configPath -Encoding UTF8
}

$shell = New-Object -ComObject WScript.Shell
function New-NEVRShortcut([string]$path) {
    $shortcut = $shell.CreateShortcut($path)
    $shortcut.TargetPath = Join-Path $installRoot 'nevr-desktop.exe'
    $shortcut.Arguments = '--config "' + $configPath + '"'
    $shortcut.WorkingDirectory = $installRoot
    $shortcut.Description = 'NEVR-Anticheat replay intelligence console'
    $shortcut.Save()
}
New-NEVRShortcut (Join-Path $startMenu 'NEVR-Anticheat.lnk')
if (-not $NoDesktopShortcut) { New-NEVRShortcut (Join-Path $desktop 'NEVR-Anticheat.lnk') }

Write-Host "NEVR-Anticheat installed to $installRoot"
Write-Host "Evidence and settings are stored safely in $dataRoot"
Start-Process -FilePath (Join-Path $installRoot 'nevr-desktop.exe') -ArgumentList @('--config', ('"' + $configPath + '"')) -WorkingDirectory $installRoot -WindowStyle Hidden
